### ISSUE TITLE
What is the Universal dataset?

### ISSUE THREAD

**Issue by Immortalin** [jik876/hifi-gan#1]
It is not specified in the paper.

**Comment by jik876** [comment]
We trained the universal model using the LibriSpeech, VCTK, and LJSpeech datasets.
We are re-training the model, which can show a little better performance. We will share as the model improves.

**Comment by ahmed-fau** [comment]
Hi @jik876 ,

When you train HiFiGAN on a multi-speaker dataset such as VCTK, did you touch some instability problems in the beginning of the training (e.g., the first 100 epochs) such that the model starts to diverge but after a while it returns back to normal behavior?

Thanks for your help!

**Comment by yileld** [comment]
> We trained the universal model using the LibriSpeech, VCTK, and LJSpeech datasets. We are re-training the model, which can show a little better performance. We will share as the model improves.

hi, can you tell us how you trained universal model ? I use same datasets but is not as good as yours.
