### ISSUE TITLE
multi-band has special frequency noise

### ISSUE THREAD

**Issue by yinhao0214** [jik876/hifi-gan#104]
hello, when i training multi-band hifigan, the generated audio always has 6k frequency noise for 24k model. 
![image](https://user-images.githubusercontent.com/11988410/144065589-86f97ed8-bc17-426c-8ac9-777741383a41.png)
 
and my training loss is decrease too slow, is it normal? thanks
![image](https://user-images.githubusercontent.com/11988410/144065818-d0cbf368-e7d3-4951-b76c-691b39005582.png)

**Comment by yygg678** [comment]
@FanhuaandLuomu  Hi,  I also meet the problem when training multi-band hifigan, the generated audio always has 4k frequency noise for 16k model. Did you solve the problem？

**Comment by yinhao0214** [comment]
solved

**Comment by Pydataman** [comment]
> solved

the reason？
