### ISSUE TITLE
Is it normal for loss to increase?

### ISSUE THREAD

**Issue by raccoonML** [jik876/hifi-gan#107]
Training mel_spec_error keeps going up. Is this normal? However, the validation mel_spec_error is decreasing. And I'm not noticing any quality problems with vocoded outputs. The dataset is VCTK.

![hifigan_training](https://user-images.githubusercontent.com/95999607/148217228-f0ac72b4-1455-4227-9c1c-6c9c78b25520.png)

**Comment by Ziyi6** [comment]
Hey bro, may I ask you how did you solve this, just interested?

**Comment by raccoonML** [comment]
Train a larger number of steps and you will see the training losses stabilize and start to decrease again. The trend will become more obvious by the time you reach 500k or 1M steps.
