### ISSUE TITLE
The training time

### ISSUE THREAD

**Issue by burcehan** [jik876/hifi-gan#13]
Hi ,thanks for your work, I  want to know the training time,how long does it take?
Thanks!

**Comment by CookiePPP** [comment]
https://github.com/jik876/hifi-gan/issues/7#issuecomment-719943371
> It took about 13-14 days to train the model up to 2,500k steps with two V100 GPUs.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
