### ISSUE TITLE
How to improve HiFi-GAN in stream TTS applications?

### ISSUE THREAD

**Issue by JohnHerry** [jik876/hifi-gan#132]
We have tried to use HiFi-GAN in steam like TTS application:  the acoustic model generate mel-spec chunk by chunk, and HiFi-GAN synthesis the audio from the chunked mel-spec.
     Our chunk is not so long, about 30+ frames per chunk. We found that the wavform generated from HiFi-GAN, at the boundary of each chunk, will get glitches.  It is seems that it had created some white noise spread all over the frequency bands.
     So is there anyway to improve the synthesis quality on  every chunk boundary?

**Comment by Miralan** [comment]
1. Maybe you can try replace vanilla convolution and tranposed convolution by causal convolution and causal tranposed covolution.
2. For longer chunk, you can use overlap strategy. For example, when you try 100ms chunk, just use 20ms(preceding) + 100ms + 20ms chunk(succeeding), then just throw 20ms audio on both sides。

**Comment by JohnHerry** [comment]
> 1. Maybe you can try replace vanilla convolution and tranposed convolution by causal convolution and causal tranposed covolution.
> 2. For longer chunk, you can use overlap strategy. For example, when you try 100ms chunk, just use 20ms(preceding) + 100ms + 20ms chunk(succeeding), then just throw 20ms audio on both sides。

Thanks for your help.
    As to The overlap strategy, We have done. It can alleviate the distortion, but not good enough.
    As to the causal convolution, I did not have experience about it.  Will it cost more computation then the transposed convolution? and can it keep the audio quality? Thanks for the information if you had tried.  I think the conv-GAN based vocoders are not good at model the periodicity of signals,  and that's why the DDSP based vocoders become hot now. But the reason we use chunked synthesis, is to keep the whole application quick to response. we do not want to introduce new computation module right now.  So we are trying to get help about imporing effect of current GAN vocoder.

**Comment by Miralan** [comment]
> 

Yes, non-autoregressive vocoder is not suitable for streaming synthesis due to the convolution receptive field increased by layers. The computation of causal convolution is almost equal to vanilla convolution, but this may slightly reduce the whole quality of audio. Maybe you can try autoregressive chunk gan vocoder([cargan](https://github.com/descriptinc/cargan)).

**Comment by Miralan** [comment]
> > 1. Maybe you can try replace vanilla convolution and tranposed convolution by causal convolution and causal tranposed covolution.
> > 2. For longer chunk, you can use overlap strategy. For example, when you try 100ms chunk, just use 20ms(preceding) + 100ms + 20ms chunk(succeeding), then just throw 20ms audio on both sides。
> 
> Thanks for your help. As to The overlap strategy, We have done. It can alleviate the distortion, but not good enough. As to the causal convolution, I did not have experience about it. Will it cost more computation then the transposed convolution? and can it keep the audio quality? Thanks for the information if you had tried. I think the conv-GAN based vocoders are not good at model the periodicity of signals, and that's why the DDSP based vocoders become hot now. But the reason we use chunked synthesis, is to keep the whole application quick to response. we do not want to introduce new computation module right now. So we are trying to get help about imporing effect of current GAN vocoder.

Yes, non-autoregressive vocoder is not suitable for streaming synthesis due to the convolution receptive field increased by layers. The computation of causal convolution is almost equal to vanilla convolution, but this may slightly reduce the whole quality of audio. Maybe you can try autoregressive chunk gan vocoder([cargan](https://github.com/descriptinc/cargan)).
