### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by burcehan** [jik876/hifi-gan#14]
Hi,thanks for your work,
I only found the pretrained models of generator, is there any pretrained models of discriminator?
Thanks!

**Comment by SanjaESC** [comment]
just some issues bellow...

https://github.com/jik876/hifi-gan/issues/5#issue-731893258

**Comment by jik876** [comment]
Thanks for your interest.
We will update the pretrained model files soon.

**Comment by jik876** [comment]
Duplicate of #5

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
