### ISSUE TITLE
Glow-tts + hifi-gan inference issue

### ISSUE THREAD

**Issue by Laay** [jik876/hifi-gan#15]
I have trained the model using Glow-TTS and was trying to infer the texts using the jupyter notebook file given in the hifi-gan directory. 

When I tried running this command:
```
#### Use finetuned HiFi-GAN with Tacotron 2, which is provided in the repo of HiFi-GAN.
!python ./hifi-gan/inference_e2e.py --checkpoint_file  ~/glow-tts/logs/base/G_100.pth

```
It gives an error:

```
Initializing Inference Process..
~/glow-tts/logs/base/config_v1.json
Loading '~/glow-tts/logs/base/G_100.pth'
Complete.
Traceback (most recent call last):
  File "./hifi-gan/inference_e2e.py", line 100, in <module>
    main()
  File "./hifi-gan/inference_e2e.py", line 96, in main
    inference(a)
  File "./hifi-gan/inference_e2e.py", line 46, in inference
    generator.load_state_dict(state_dict_g['generator'])
KeyError: 'generator'
```
can anyone tell why this error is showing and how can I solve this ?

**Comment by CookiePPP** [comment]
`inference_e2e.py` is for converting `.npy` spectrogram files into audio. Your `--checkpoint_file` should be the HiFi-GAN checkpoint not the Glow-TTS one.

**Comment by jik876** [comment]
Referencing the file below in Glow-TTS repository would be helpful to implement inference.

[inference_hifigan.ipynb](https://github.com/jaywalnut310/glow-tts/blob/master/inference_hifigan.ipynb)

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
