### ISSUE TITLE
log  mel  spectrum  and  linear  mel  spectrum

### ISSUE THREAD

**Issue by burcehan** [jik876/hifi-gan#18]
Hi ,thanks for your work,
Can I choose to use linear mel spectrum, log mel spectrum and linear mel spectrum,which one is better?
Thanks!

**Comment by jik876** [comment]
Thanks for your interest.
We haven't experimented with linear mel-spectrograms, so it's hard to comment what the results will be.
However, it is worth noting that there are many experiments using log scale spectrograms with good results.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
