### ISSUE TITLE
Buzzing noise

### ISSUE THREAD

**Issue by burcehan** [jik876/hifi-gan#19]
Hi ,Thanks for your work
I have trained 50k steps start from scratch,the config is v1,there is a buzz noise in the the generated audio , can I get rid of the noise if I continue training,do you have any suggestions?
Thanks for your help

**Comment by Miralan** [comment]
I think you should continue to train. 50k is not enough.

**Comment by jik876** [comment]
Thanks for your interest.
I would recommend you train the model further. 50k is too early to synthesize high quality audio.
In our experience, when the model was trained up to 500k steps, it was able to synthesize fairly good quality audio.
The quality will be improved as training progresses after 500k steps, if you continue training.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
