### ISSUE TITLE
Errors when trying to load pretrained Universal model

### ISSUE THREAD

**Issue by wookladin** [jik876/hifi-gan#2]
Hi. I'm working on `torch==1.4.0` environment, as you wrote in `requirement.txt`
I successfully inference with your pretrained `generator_v1` & `finetuned generator_v1`

However, I tried to load your universal generator model, following error occured.

`RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fec128e9193 in /home/kwkim/six/lib64/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7fec15c799eb in /home/kwkim/six/lib64/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7fec15c7ac04 in /home/kwkim/six/lib64/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c53a6 (0x7fec5e13b3a6 in /home/kwkim/six/lib64/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2961c4 (0x7fec5dd0c1c4 in /home/kwkim/six/lib64/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #38: __libc_start_main + 0xf5 (0x7fecbc751445 in /lib64/libc.so.6)
frame #39: python3() [0x400c40]`

I think your universal model was trained and saved in higher torch version than 1.6.0.
Could you please check this error?

Thank you.

**Comment by jik876** [comment]
Thanks for letting us know. We updated the pretrained model file. Please download again.
