### ISSUE TITLE
Add the torch pip install full command

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [jik876/hifi-gan#20]
maybe something like:
pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
 
just a suggestion.BTW,what is the os for the original setup?

**Comment by jik876** [comment]
Thanks for your interest!
That's a good idea, but I think it's okay to use the requirements file for version 1.4. 
Please let me know if there are any inconveniences or problems that I haven't noticed when using the requirements file.
We used Ubuntu 16 and 18 in our experiments.

**Comment by xwaeaewcrhomesysplug** [comment]
nah it is ok just a few searches away.I will close this then.^^
