### ISSUE TITLE
Training times v1 vs. v2 vs. v3?

### ISSUE THREAD

**Issue by serg06** [jik876/hifi-gan#21]
Hello, I see it took you this amount of time to train v1:

> It took about 13-14 days to train the model up to 2,500k steps with two V100 GPUs.

Since v2 and v3 have faster inference, does that mean training them would be faster too?

**Comment by jik876** [comment]
Thanks for your interest!
Yes. Although V2 and V3 are trained faster than V1, there is no difference as much as the difference in inference speed because the discriminator takes longer during training.
When training V3, the training time is shortened by approximately 13~14% compared to V1.

**Comment by serg06** [comment]
Awesome, thank you @jik876!
