### ISSUE TITLE
Why does the mel.npy file I trained with the tacotron2 model not match the dimensions in hifi-gan?

### ISSUE THREAD

**Issue by c9412600** [jik876/hifi-gan#27]
I trained the tacotron2 model to produce mel_**.npy ,but in this model, the error of dimension mismatch is reported
`python3 inference_e2e.py --checkpoint_file cp_hifigan-1208-test/g_00036000 
Initializing Inference Process..
cp_hifigan-1208-test/g_00036000
Loading 'cp_hifigan-1208-test/g_00036000'
Complete.
Removing weight norm...
Traceback (most recent call last):
  File "inference_e2e.py", line 90, in <module>
    main()
  File "inference_e2e.py", line 86, in main
    inference(a)
  File "inference_e2e.py", line 51, in inference
    y_g_hat = generator(x)
  File "/home/zhchen/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhchen/hifi-gan-master/models.py", line 101, in forward
    x = self.conv_pre(x)
  File "/home/zhchen/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhchen/python3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 200, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3-dimensional input for 3-dimensional weight 128 80, but got 2-dimensional input of size [288, 80] instead`

**Comment by jik876** [comment]
It is because of the shape of the input data.
Insert the following code at line 50 of inference_e2e.py file and try again.

            if len(x.shape) < 3:
                x = x.unsqueeze(0)

We will update it soon.

**Comment by Miralan** [comment]
> It is because of the shape of the input data.
> Insert the following code at line 50 of inference_e2e.py file and try again.
> 
> ```
>         if len(x.shape) < 3:
>             x = x.unsqueeze(0)
> ```
> 
> We will update it soon.

Maybe below better
```
          if len(x.shape) < 3:
              x = x.unsqueeze(0)
          if not x.shape[1] == h.num_mels:
              x = x.tranpose(1, 2) 
```

**Comment by c9412600** [comment]
> > It is because of the shape of the input data.
> > Insert the following code at line 50 of inference_e2e.py file and try again.
> > ```
> >         if len(x.shape) < 3:
> >             x = x.unsqueeze(0)
> > ```
> > 
> > 
> > We will update it soon.
> 
> Maybe below better
> 
> ```
>           if len(x.shape) < 3:
>               x = x.unsqueeze(0)
>           if not x.shape[1] == h.num_mels:
>               x = x.tranpose(1, 2) 
> ```

Thanks a lot! It works!

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.

**Comment by McTi** [comment]
Just a heads up that there's a typo in that code snippet... tranpose -> tran**s**pose

Should be:

```
          if len(x.shape) < 3:
              x = x.unsqueeze(0)
          if not x.shape[1] == h.num_mels:
              x = x.transpose(1, 2) 

```
