### ISSUE TITLE
Specific environment version

### ISSUE THREAD

**Issue by peacefulxy** [jik876/hifi-gan#28]
When training I have a runtime error: : cuDNN error: CUDNN_STATUS_EXECUTION_FAILED. Could you please provide specific version of your environment, including python, cuda and cudnn? Thank you very much.

**Comment by jik876** [comment]
Sorry for late reply.
We used python3.7, pytorch1.6 and CUDA 10.1 most often in our experiments.
It would be a good try to reinstall pytorch.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.

**Comment by chikiuso** [comment]
Hi, I found the error "RuntimeError: CUDA error: no kernel image is available for execution on the device" with this setting, or anything I did wrong on the installation? thanks

**Comment by chikiuso** [comment]
The full error message is as below, may I seek your help how could I solve it? thanks : 

checkpoints directory :  cp_hifigan
Epoch: 1
/root/hifi-gan/meldataset.py:15: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
/root/hifi-gan/meldataset.py:15: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
/root/hifi-gan/meldataset.py:15: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
/root/hifi-gan/meldataset.py:15: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 267, in main
    train(0, a, h)
  File "train.py", line 122, in train
    y_g_hat = generator(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/hifi-gan/models.py", line 101, in forward
    x = self.conv_pre(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 714, in _call_impl
    result = hook(self, input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/weight_norm.py", line 55, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/weight_norm.py", line 18, in compute_weight
    return _weight_norm(v, g, self.dim)
RuntimeError: CUDA error: no kernel image is available for execution on the device
