### ISSUE TITLE
Why use those mel spectrogram configurations?

### ISSUE THREAD

**Issue by prattcmp** [jik876/hifi-gan#29]
I'm particularly curious about the choices to use:
```
fmin=0
n_fft = win_length = 1024
mulaw.bits = 9
```

Were these values chosen arbitrarily or are there some pros/cons (tradeoffs) to these values?

**Comment by CookiePPP** [comment]
> fmin=0
> n_fft = win_length = 1024

These are chosen so the vocoder can be used with the [NVIDIA/tacotron2 repo](https://github.com/NVIDIA/tacotron2) and any other repo using the 50ms window length that's semi-standard in this space.

mulaw is not used in this repo to my knowledge. I didn't find a mention of it either in the code or paper.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
