### ISSUE TITLE
mel spectrum loss VS  stft loss

### ISSUE THREAD

**Issue by nukes** [jik876/hifi-gan#31]
Hi,
thanks for your great work. In paper you mentioned that using the mel spectrum loss to get a more stable and efficient training. The multi-resolution STFT loss used in parallel-wavegan/mb-megan seems can achieve the same goal.
My question is have you tried the stft loss instead the mel loss? did you observe the differences(if you tried)?

Thanks.

**Comment by jik876** [comment]
Thanks for your interest.
We experimented with STFT loss and observed that the quality was worse than with the mel-spectrogram loss in the early stage.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if you need additional comments.
