### ISSUE TITLE
How to train a new model with 8k data

### ISSUE THREAD

**Issue by lightwithshadow** [jik876/hifi-gan#37]
Thanks for your contribution. What parameters need to be modified to train a new model with 8K data

**Comment by jik876** [comment]
Thanks for your interest!!
#8, #12 will be helpful to you.
Make the parameters related to FFT smaller, set `upsample_rates` to fit `hop_size`, set `segment_size` to be a multiple of `hop_size` and adjust `sampling_rate` and `fmax`.
Adjusting `upsample_kernel_sizes` according to `upsample_rates` is recommended, but not required. It's a good idea to experiment to see which is better.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if anyone needs additional comments.
