### ISSUE TITLE
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by leminhnguyen** [jik876/hifi-gan#44]
I've encountered the following error when I'm trying to fine-tuning mel-spec from Tacotron2
````
Traceback (most recent call last):
  File "train.py", line 276, in <module>
    main()
  File "train.py", line 272, in main
    train(0, a, h)
  File "train.py", line 127, in train
    y_g_hat = generator(x)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/nguyenlm/Projects/hifi-gan-clone/models.py", line 101, in forward
    x = self.conv_pre(x)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
````

**Comment by Miralan** [comment]
Maybe you can use `x = x.to(torch.float32)` before `y_g_hat = generator(x)`

**Comment by leminhnguyen** [comment]
@Miralan Thanks for your reply. After adding `x = x.to(torch.float32)` before `y_g_hat = generator(x)` I've faced with another problem:
```
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    main()
  File "train.py", line 273, in main
    train(0, a, h)
  File "train.py", line 117, in train
    for i, batch in enumerate(train_loader):
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home2/nguyenlm/Projects/hifi-gan-clone/meldataset.py", line 168, in __getitem__
    center=False)
  File "/home2/nguyenlm/Projects/hifi-gan-clone/meldataset.py", line 50, in mel_spectrogram
    if torch.min(y) < -1.:
RuntimeError: invalid argument 1: cannot perform reduction function min on tensor with no elements because the operation does not have an identity at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:345
```
In addition to, I want to ask you some questions. I've got spectrogram from tacotron2 by 
`np.save(f"{mel_folder}/{file}.npy", mel_outputs_postnet.data.cpu().numpy()[0], allow_pickle=False)`.
But I saw somewhere people use 
`np.save(f"{mel_folder}/{file}.npy", mel_outputs_postnet.data.cpu().numpy()[0].T, allow_pickle=False)` (I guess `.T` for transpose). 

So there are any problem with my way or both are acceptable ? Thanks in advance.

**Comment by Miralan** [comment]
Transpose operation can be used anytime before feed it to model, so it doesn't matter.
`RuntimeError: invalid argument 1: cannot perform reduction function min on tensor with no elements because the operation does not have an identity`, it seem like that the tensor is empty, so make sure you wav path is right. And you can also print it shape and value in mel_spectrogram function to check it right or not. Like this:
```python
def mel_spectrogram(y, n_fft, num_mels, sampling_rate, hop_size, win_size, fmin, fmax, center=False):
    print(y)
    print(y.shape)
    if torch.min(y) < -1.:
    ....
```

**Comment by leminhnguyen** [comment]
@Miralan Thanks you, I inspected my files and I saw one Tensor is empty so I've removed that file and try to run again. I ran successfully at 3 first epochs, but after that I faced with 
```Traceback (most recent call last):
  File "train.py", line 274, in <module>
    main()
  File "train.py", line 270, in main
    train(0, a, h)
  File "train.py", line 115, in train
    for i, batch in enumerate(train_loader):
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 81, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 57, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 8192 and 3577 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
```
It seems after each epoch the size of tensor changed. So I must reshape tensor or do something before each epoch. Thanks a lot

**Comment by Miralan** [comment]
> @Miralan Thanks you, I inspected my files and I saw one Tensor is empty so I've removed that file and try to run again. I ran successfully at 3 first epochs, but after that I faced with
> 
> ```
>   File "train.py", line 274, in <module>
>     main()
>   File "train.py", line 270, in main
>     train(0, a, h)
>   File "train.py", line 115, in train
>     for i, batch in enumerate(train_loader):
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
>     return self._process_data(data)
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
>     data.reraise()
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
>     raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
>     return [default_collate(samples) for samples in transposed]
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 81, in <listcomp>
>     return [default_collate(samples) for samples in transposed]
>   File "/home/kynh/anaconda3/envs/nguyenlm_hifigan/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 57, in default_collate
>     return torch.stack(batch, 0, out=out)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 8192 and 3577 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
> ```
> 
> It seems after each epoch the size of tensor changed. So I must reshape tensor or do something before each epoch. Thanks a lot

It seems like that some wav files is less than 8192 sample points, try to remove them or padding zeros.

**Comment by leminhnguyen** [comment]
@Miralan Thanks you. After reading the code in `meldataset.py` file, I think there are some bugs in the code at the line `audio = audio[:, mel_start * self.hop_size:(mel_start + frames_per_seg) * self.hop_size]`. When I run the code I realize some the potential problems.
1. Assume the audio size is `torch.Size([1, 36206])`, `frames_per_seg=32` and random `mel_start=113`. So we will slice `audio[28928:37120]`. It means the shape of audio after slicing is `torch.Size([1, 7278]` (because upper bound is 36206). That leads to `RuntimeError: mismatch dimension`. So as you said we can pad zeros
2. Assume the audio size is `torch.Size([1, 72972])`, `frames_per_seg=32` and random `mel_start=300`. So we will slice `audio[76800:84992]`. It means the shape of audio after slicing is `torch.Size([1, 0]` (because we slice out of range of the audio). That leads to empty tensor. Again, we can overcome this problem by padding zeros, but I wonder if there are many empty tensors like that and filled out by zeros, it significantly affect to the quality of training or fine-tuning ?

**Comment by Miralan** [comment]
> @Miralan Thanks you. After reading the code in `meldataset.py` file, I think there are some bugs in the code at the line `audio = audio[:, mel_start * self.hop_size:(mel_start + frames_per_seg) * self.hop_size]`. When I run the code I realize some the potential problems.
> 
> 1. Assume the audio size is `torch.Size([1, 36206])`, `frames_per_seg=32` and random `mel_start=113`. So we will slice `audio[28928:37120]`. It means the shape of audio after slicing is `torch.Size([1, 7278]` (because upper bound is 36206). That leads to `RuntimeError: mismatch dimension`. So as you said we can pad zeros
> 2. Assume the audio size is `torch.Size([1, 72972])`, `frames_per_seg=32` and random `mel_start=300`. So we will slice `audio[76800:84992]`. It means the shape of audio after slicing is `torch.Size([1, 0]` (because we slice out of range of the audio). That leads to empty tensor. Again, we can overcome this problem by padding zeros, but I wonder if there are many empty tensors like that and filled out by zeros, it significantly affect to the quality of training or fine-tuning ?

My persponal advice is that preprocessing your wav files cutoff unnecessary parts (edge) or pad zeros to keep `len(audio) / len(mel) = hop_size`. 
And in `meldataset.py`
```python
            if self.split:
                frames_per_seg = math.ceil(self.segment_size / self.hop_size)

                if audio.size(1) >= self.segment_size:
                    mel_start = random.randint(0, mel.size(2) - frames_per_seg - 1)
                    mel = mel[:, :, mel_start:mel_start + frames_per_seg]
                    audio = audio[:, mel_start * self.hop_size:(mel_start + frames_per_seg) * self.hop_size]
                else:
                    mel = torch.nn.functional.pad(mel, (0, frames_per_seg - mel.size(2)), 'constant')
                    audio = torch.nn.functional.pad(audio, (0, self.segment_size - audio.size(1)), 'constant')
```
If you make sure `len(audio) / len(mel) = hop_size`, most of situations you don't need pad zeros.

**Comment by leminhnguyen** [comment]
@Miralan Thanks a lot for your time. I'm a newbie and I'll appreciate if you give me some reference link for preprocessing audio (like cutoff edge technique) or you can explain a little bit more details (about technique) how can I preprocess the audio ?
Thanks in advance

**Comment by Miralan** [comment]
> @Miralan Thanks a lot for your time. I'm a newbie and I'll appreciate if you give me some reference link for preprocessing audio (like cutoff edge technique) or you can explain a little bit more details (about technique) how can I preprocess the audio ?
> Thanks in advance

Your wav files should be almost equal mel_nums * hop_size. For example, raw wav: [4004] , mel: [200, 80], hop_size: 200.
So you can use wav = wav[2 : -2]; If raw wav is [3996],  just pad two zeros at each edge of this wav. Then `len(wav) % len(mel) == 0`. I think it help avoid some mismatch errors.

**Comment by Alexey322** [comment]
@Miralan
You can just replace the tacotron 2 get mel spectrogram function by copying it from hi fi gun repository and finetune your tacotron 2 model.

**Comment by jik876** [comment]
I close this as there are no recent updates. Please reopen if anyone needs additional comments.

**Comment by yulijun1220** [comment]
@leminhnguyen  I'v encountered the same error. Do you have any suggestion on this?
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    val_percent=args.val / 100)
  File "train.py", line 128, in train_net
    loss.backward()
  File "C:\ProgramData\Anaconda3\envs\pytorch-py3.7\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\ProgramData\Anaconda3\envs\pytorch-py3.7\lib\site-packages\torch\autograd\__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Expected tensor for argument #1 'grad_output' to have the same type as tensor for argument #2 'weight'; but type torch.cuda.HalfTensor does not equal torch.cuda.FloatTensor (while checking arguments for cudnn_convolution_backward_input)
The source code link of train.py is [https://github.com/milesial/Pytorch-UNet/blob/master/train.py](url)

**Comment by a897456** [comment]
> 
> In addition to, I want to ask you some questions. I've got spectrogram from tacotron2 by `np.save(f"{mel_folder}/{file}.npy", mel_outputs_postnet.data.cpu().numpy()[0], allow_pickle=False)`. But I saw somewhere people use `np.save(f"{mel_folder}/{file}.npy", mel_outputs_postnet.data.cpu().numpy()[0].T, allow_pickle=False)` (I guess `.T` for transpose).
> 
> 

Can you point out where in tacotron2 you mentioned this code? I get npy through librosa, it doesn't work on HIFIGAN, so I still need to get npy through tacotron2, can you help me quickly locate the code about how to get npy in tacotron2?
