### ISSUE TITLE
HiFi-GAN TFLite Model

### ISSUE THREAD

**Issue by tulasiram58827** [jik876/hifi-gan#45]
Hi @jik876 @Edresson 

We(@sayakpaul) converted the pre-trained PyTorch model of the HiFi-GAN to TFLite Format. Thanks for providing the pre-trained models. You can use this [Notebook](https://github.com/tulasiram58827/TTS_TFLite/blob/main/HiFi-GAN.ipynb) to convert all the available pre-trained models to TFLite Format. If you are interested in any other models you can visit this [Repository](https://github.com/tulasiram58827/TTS_TFLite/). We also provided [benchmark results](https://github.com/tulasiram58827/TTS_TFLite#model-benchmarks) of HiFi-GAN TFLite Model w.r.t to other models like Parallel WaveGAN, MelGAN, MB-MelGAN.

Models will be soon published to TensorFlow Hub.

**Comment by nukes** [comment]
Great work! Did you listen the generated audio across the models? From the quality perspective, which one is better?

**Comment by tulasiram58827** [comment]
@nukes I just added all combinations of audio samples. You can refer to this [folder](https://github.com/tulasiram58827/TTS_TFLite/tree/main/audio_samples) and decide yourself or you can visit this [sound cloud](https://soundcloud.com/tulasi-ram-887761209) folder to listen without dowloading.
