### ISSUE TITLE
How to train on 48khz data?

### ISSUE THREAD

**Issue by 980202006** [jik876/hifi-gan#55]
Hi, thank you for the work. 
When I train the model ,I meet the follow error.
  File "G:\xiazai\hifi-gan-master\hifi-gan-master\models.py", line 255, in feature_loss
    loss += torch.mean(torch.abs(rl - gl))
RuntimeError: The size of tensor a (1366) must match the size of tensor b (1362) at non-singleton dimension 2

This is the config
`{
    "resblock": "1",
    "num_gpus": 0,
    "batch_size": 16,
    "learning_rate": 0.0002,
    "adam_b1": 0.8,
    "adam_b2": 0.99,
    "lr_decay": 0.999,
    "seed": 1234,

    "upsample_rates": [8,5,3,2],
    "upsample_kernel_sizes": [16,10,6,4],
    "upsample_initial_channel": 512,
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],

    "segment_size": 8192,
    "num_mels": 80,
    "num_freq": 1025,
    "n_fft": 2048,
    "hop_size": 240,
    "win_size": 1200,

    "sampling_rate": 48000,

    "fmin": 80,
    "fmax": 7600,
    "fmax_for_loss": null,

    "num_workers": 4,

    "dist_config": {
        "dist_backend": "nccl",
        "dist_url": "tcp://localhost:54321",
        "world_size": 1
    }
}
`

**Comment by 980202006** [comment]
In my experience, the segment_size should  be more than 1/3 sample rate. I use 8192,it does not work.But for 24000 or 19200, it work. Why?

**Comment by CookiePPP** [comment]
I think `segment_size` should be a multiple of `hop_size`
24000/240 = 100
19200/240 =  80
8192/240 = 34.133333333333333333333333333333‬
8160‬/240 = 34

**Comment by 980202006** [comment]
yes, other size like 9600 does not work ,too. It may be a larger segment size is necessary.
