### ISSUE TITLE
error when finetune hifigan with mel generated by fastspeech

### ISSUE THREAD

**Issue by yt605155624** [jik876/hifi-gan#56]
closed

**Comment by yt605155624** [comment]
I gen mel from fastspeech by the result of force alignment as duration

**Comment by yt605155624** [comment]
sorry I have find why, the mel 's shape should be (1,120,148) but not (148, 120)

**Comment by v-nhandt21** [comment]
@yt605155624 , Hi, Have you handle with this miss match problem, how can I deal with difference in frame of ground truth and the mel generated by fastspeech
