### ISSUE TITLE
What is num_freq?

### ISSUE THREAD

**Issue by wizardk** [jik876/hifi-gan#73]
I didn't see this parameter used in the code.

**Comment by Charlottecuc** [comment]
`num_freq` is `fft_bins`. Normally it should be (n_fft // 2 + 1) I guess.

**Comment by Miralan** [comment]
> `num_freq` is `fft_bins`. Normally it should be (n_fft // 2 + 1) I guess.

I think it may be the end points of `fft_bins`. For example, when `fft_bins` is [0, 1), [1, 2), the `num_freq` should be 3 (0, 1, 2).
