### ISSUE TITLE
window size is hardcoded (44khz HiFi-GAN)

### ISSUE THREAD

**Issue by rafaelvalle** [jik876/hifi-gan#8]
Congratulations and thank you for this great work. 
We were able to easily adapt it (doubling fft params and changing upsample rates to [8,8,4,2]) to produce 44khz 16bit audio with very high quality.

The line below has the window size hard coded to 1024. It should be replaced with win_size.
https://github.com/jik876/hifi-gan/blob/6b97a5fcf8cc9068188e7bcf720187394e7884ce/meldataset.py#L59

**Comment by jik876** [comment]
Thank you very much! Your work has helped us a lot.

It would be very good information for those who want to apply HiFi-GAN to synthesize 44kHz audio.
I've updated the code you mentioned. Thanks for letting us know!

**Comment by Megh-Thakkar** [comment]
Hi, which params comprise the 'fft_params'?

Thank you.
