### ISSUE TITLE
Training multi-speaker Hifi-GAN

### ISSUE THREAD

**Issue by JohnHerry** [jik876/hifi-gan#95]
HI, all
     Is there any practice to show that multi-speaker Hifi-GAN may get better generalization to unseen speaker? Or that get better MOS on both gender? What is the better config on multi-speaker dataset?

**Comment by JohnHerry** [comment]
Close

**Comment by ysujiang** [comment]
> HI, all Is there any practice to show that multi-speaker Hifi-GAN may get better generalization to unseen speaker? Or that get better MOS on both gender? What is the better config on multi-speaker dataset?

the same question with you. Have you got a best answer?

**Comment by JohnHerry** [comment]
> > HI, all Is there any practice to show that multi-speaker Hifi-GAN may get better generalization to unseen speaker? Or that get better MOS on both gender? What is the better config on multi-speaker dataset?
> 
> the same question with you. Have you got a best answer?

默认配置就行了，它的泛化还不错的。如果要效果好最好还是不要用在unseen上；虽然可以合成unseen的，但是比之带有相关语音训练数据的，效果还是差一些。
