### ISSUE TITLE
How to decide when to stop training?

### ISSUE THREAD

**Issue by JohnHerry** [jik876/hifi-gan#98]
Is there any suggestion when to stop training? some times It seems that Loss(G) is still descreasing while the Loss(D) is raising.
![96fbd0cbfffb7443ddd8546fa1dfda5](https://user-images.githubusercontent.com/8011802/133546643-f9b38437-446b-4ef9-a0c1-287eab184aa2.png)
![fc9ff7921e31837349eb63af784b92e](https://user-images.githubusercontent.com/8011802/133546669-6245f7ac-8a02-4da6-89e3-bdba3bb5c09f.png)
![947a35659327c8ca4164761f38e43e4](https://user-images.githubusercontent.com/8011802/133546688-cf8fbdb3-d6f4-4bd4-824e-b3e49d238841.png)

**Comment by JohnHerry** [comment]
Close

**Comment by Ziyi6** [comment]
Did you find when to stop training? The mel-spectrogram loss is still decreasing after training 10 days.
